---
apiVersion: v1
kind: Service
metadata:
  name: sec-pr-tool
  namespace: ops
  labels:
    app: sec-pr-tool
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: sec-pr-tool
